Repository EYBlockchain/nightfall_3, pull requests merged in 2021-11, with the labels that each got.

#256 Stateless sibling paths
  common-files/classes/timber.mjs
  test/timber.test.mjs
Labels: One more approval needed

#268 Add queue to client
  common-files/utils/event-queue.mjs
  nightfall-client/package-lock.json
  nightfall-client/package.json
  nightfall-client/src/event-handlers/index.mjs
  nightfall-client/src/event-handlers/subscribe.mjs
  nightfall-client/src/index.mjs
  nightfall-optimist/src/index.mjs
  nightfall-optimist/src/routes/block.mjs
Labels: One more approval needed

#275 github workflow cron job for infura ropsten deployment and integration test run
  .github/workflows/infura-ropsten-deploy-cron-job.yml
  test/http.mjs
  test/neg-http.mjs
  test/utils.mjs
Labels: One more approval needed

#276 Daveroga/api status widthdraws
  cli/lib/nf3.mjs
  doc/lib/nf3.mjs.html
  nightfall-client/src/app.mjs
  nightfall-client/src/routes/commitment.mjs
  nightfall-client/src/routes/index.mjs
  nightfall-client/src/routes/valid-withdrawal.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-client/src/services/transfer.mjs
  nightfall-client/src/services/valid-withdrawal.mjs
  nightfall-client/src/services/withdraw.mjs
  nightfall-client/src/utils/optimist.mjs
  nightfall-deployer/contracts/Shield.sol
  test/e2e/nightfall-sdk.test.mjs
Labels: One more approval needed

#278 Add second historic root
  common-files/classes/transaction.mjs
  config/default.js
  config/timber.js
  nightfall-client/src/services/transfer.mjs
  nightfall-client/src/services/withdraw.mjs
  nightfall-deployer/circuits/common/hashes/sha256/hash4608.zok
  nightfall-deployer/circuits/common/hashes/sha256/pad4096ThenHash.zok
  nightfall-deployer/circuits/double_transfer.zok
  nightfall-deployer/contracts/Challenges.sol
  nightfall-deployer/contracts/ChallengesUtil.sol
  nightfall-deployer/contracts/Structures.sol
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/challenges.mjs
  nightfall-optimist/src/services/transaction-checker.mjs
  test/utils.mjs
Labels: One more approval needed

#264 feat: deterministic zkp keys
  cli/lib/nf3.mjs
  cli/package-lock.json
  cli/package.json
  doc/lib/nf3.mjs.html
  nightfall-client/package-lock.json
  nightfall-client/package.json
  nightfall-client/src/routes/generate-keys.mjs
  nightfall-client/src/services/keys.mjs
  package-lock.json
  package.json
  test/chain-reorg.mjs
  test/http.mjs
  test/neg-http.mjs
  test/rollback-resync.test.mjs
  test/tx-gas.mjs
Labels: One more approval needed

#279 client chain-reorg functionality
  doc/chain-reorgs.md
  docker-compose.host.docker.internal.yml
  nightfall-client/src/event-handlers/block-proposed.mjs
  nightfall-client/src/event-handlers/chain-reorg.mjs
  nightfall-client/src/event-handlers/index.mjs
  nightfall-client/src/event-handlers/subscribe.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-optimist/src/event-handlers/block-proposed.mjs
  nightfall-optimist/src/event-handlers/chain-reorg.mjs
  nightfall-optimist/src/services/database.mjs
  test/chain-reorg.mjs
  timber/src/filter-controller.mjs
Labels: One more approval needed

#284 David/wallet keys
  README.md
  cli/.babelrc
  cli/lib/index.mjs
  cli/lib/nf3.mjs
  cli/package-lock.json
  cli/package.json
  cli/src/challenger.mjs
  cli/src/liquidity-provider.mjs
  cli/src/proposer.mjs
  test/e2e/nightfall-sdk.test.mjs
  wallet/README.md
  wallet/package-lock.json
  wallet/package.json
  wallet/src/constants.js
  wallet/src/store/index.js
  wallet/src/store/settings/settings.actions.js
  wallet/src/store/settings/settings.reducer.js
  wallet/src/utils/lib/local-storage.js
  wallet/src/views/login/components/create-wallet.view.jsx
  wallet/src/views/login/login.view.jsx
  wallet/src/views/transactions/components/header-menu/account-settings.view.jsx
  wallet/src/views/transactions/components/header-menu/header-menu.view.jsx
  wallet/test/README.md
  wallet/test/helpers/wallet.py
  wallet/test/wallet_test.py
Labels: One more approval needed

#291 Docker images and release
  .github/workflows/publish-docker-images.yml
  client.Dockerfile
  deployer.Dockerfile
  docker-compose.images.example.yml
  optimist.Dockerfile
  worker.Dockerfile
Labels: One more approval needed

#308 setInterval to fetch token balance
  wallet/src/constants.js
  wallet/src/views/login/login.view.jsx
  wallet/src/views/transactions/components/wallet-info/wallet-info.view.jsx
Labels: wallet, One more approval needed

#306 Local <> contract transaction hash mismatch
  common-files/classes/transaction.mjs
Labels: bug

#314 fix: get proposers collection and register proposer
  nightfall-deployer/contracts/Proposers.sol
  nightfall-optimist/src/routes/proposer.mjs
Labels: One more approval needed

#321 fix: typo in actions file
  .github/workflows/publish-docker-images.yml
Labels: One more approval needed

#322 David/approve
  README.md
  cli/lib/abi.mjs
  cli/lib/abis/ERC1155.mjs
  cli/lib/abis/ERC20.mjs
  cli/lib/abis/ERC721.mjs
  cli/lib/constants.mjs
  cli/lib/index.mjs
  cli/lib/nf3.mjs
  cli/lib/tokens.mjs
  cli/lib/units.mjs
  cli/src/index.mjs
  nightfall-deployer/contracts/Shield.sol
  wallet/README.md
  wallet/src/constants.js
  wallet/src/store/token/token.actions.js
  wallet/src/store/token/token.reducer.js
  wallet/src/store/transactions/transactions.thunks.js
  wallet/src/utils/lib/local-storage.js
  wallet/src/utils/tokens.js
  wallet/src/views/transactions/components/transactions/transactions-modal.view.jsx
  wallet/src/views/transactions/components/wallet-info/wallet-info.view.jsx
Labels: One more approval needed

#301 Fix multiple wallet minor issues
  cli/lib/nf3.mjs
  wallet/src/store/index.js
  wallet/src/store/settings/settings.actions.js
  wallet/src/store/settings/settings.reducer.js
  wallet/src/views/login/components/create-wallet.view.jsx
  wallet/src/views/login/login.view.jsx
  wallet/src/views/transactions/components/header-menu/account-settings.view.jsx
Labels: One more approval needed
