Repository EYBlockchain/nightfall_3, pull requests merged in 2022-12, with the labels that each got.

#1292 Client and deployer issues
  nightfall-client/src/index.mjs
  nightfall-deployer/src/circuit-setup.mjs
Labels: One more approval needed

#1272 Fees are only paid in L2
  cli/lib/constants.mjs
  cli/lib/nf3.mjs
  common-files/constants/constants.json
  config/default.js
  nightfall-client/src/event-handlers/block-proposed.mjs
  nightfall-client/src/routes/commitment.mjs
  nightfall-client/src/services/burn.mjs
  nightfall-client/src/services/deposit.mjs
  nightfall-client/src/services/tokenise.mjs
  nightfall-client/src/services/transfer.mjs
  nightfall-client/src/services/withdraw.mjs
  nightfall-client/src/utils/submitTransaction.mjs
  nightfall-deployer/circuits/depositfee.circom
  nightfall-deployer/contracts/Key_Registry.sol
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/contracts/State.sol
  nightfall-deployer/contracts/Structures.sol
  nightfall-deployer/package-lock.json
  nightfall-deployer/src/circuit-setup.mjs
  test/e2e/protocol/proposer.test.mjs
  test/e2e/tokens/erc1155.test.mjs
  test/e2e/tokens/erc20.test.mjs
  test/e2e/tokens/erc721.test.mjs
  test/ping-pong/index.mjs
  test/unit/SmartContracts/shield.unit.test.mjs
  test/unit/SmartContracts/state.unit.test.mjs
  test/unit/utils/stateStorage.mjs
  wallet/src/components/BridgeComponent/index.jsx
  wallet/src/nightfall-browser/services/deposit.js
  wallet/src/nightfall-browser/services/transfer.js
  wallet/src/nightfall-browser/services/withdraw.js
  worker/src/index.mjs
Labels: SDK

#1259 Add extended key usage checks
  apps/utils/oid-encoder.mjs
  cli/lib/nf3.mjs
  config/default.js
  doc/adding_certificates.md
  doc/x509.md
  nightfall-client/src/routes/x509.mjs
  nightfall-client/src/services/x509.mjs
  nightfall-deployer/contracts/X509.sol
  nightfall-deployer/migrations/2_deploy_upgradeable.js
  package-lock.json
  package.json
  test/unit/SmartContracts/X509.unit.test.mjs
  test/unit/utils/Nightfall_end_user_extended.cer
  test/unit/utils/Nightfall_end_user_extended.der
  test/unit/utils/Nightfall_end_user_policies.cer
  test/unit/utils/Nightfall_end_user_policies.der
  test/unit/utils/digicert_document_signing_mock.cer
  test/unit/utils/digicert_document_signing_mock.der
  test/unit/utils/entrust_document_signing_mock.cer
  test/unit/utils/entrust_document_signing_mock.der
  test/x509.test.mjs
Labels: Required PR

#1287 Add withdraw, lazy optimist, bad client to ping pong
  .github/workflows/on-pull-request-master.yml
  apps/challenger/config/default.js
  apps/challenger/docker-entrypoint.sh
  apps/proposer/config/default.js
  apps/proposer/docker-entrypoint.sh
  docker/challenger.Dockerfile
  docker/docker-compose.multiproposer-test.yml
  example.multiproposer-test.env
  test/ping-pong/index.mjs
  test/ping-pong/ping-pong.test.mjs
Labels: One more approval needed, Required PR

#1297 Optimist fixes
  nightfall-optimist/src/event-handlers/block-proposed.mjs
  nightfall-optimist/src/event-handlers/rollback.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  nightfall-optimist/src/services/database.mjs
  test/adversary.test.mjs
Labels: Required PR

#1293 move commitment selection tests
  cli/lib/nf3.mjs
  test/client/commitments.test.mjs
  test/e2e/tokens/l2tokenisation.test.mjs
Labels: One more approval needed

#1299 Optimist simplification
  nightfall-optimist/src/event-handlers/block-proposed.mjs
  nightfall-optimist/src/event-handlers/rollback.mjs
  nightfall-optimist/src/event-handlers/transaction-submitted.mjs
  nightfall-optimist/src/services/check-block.mjs
  nightfall-optimist/src/services/database.mjs
  nightfall-optimist/src/services/transaction-checker.mjs
  test/adversary/transpile-optimist-adversary.mjs
Labels: One more approval needed

#1319 User can provide either fee or value commitments
  cli/lib/nf3.mjs
  nightfall-client/src/routes/burn.mjs
  nightfall-client/src/routes/deposit.mjs
  nightfall-client/src/routes/tokenise.mjs
  nightfall-client/src/routes/transfer.mjs
  nightfall-client/src/routes/withdraw.mjs
  nightfall-client/src/services/burn.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-client/src/services/database.mjs
  nightfall-client/src/services/deposit.mjs
  nightfall-client/src/services/tokenise.mjs
  nightfall-client/src/services/transfer.mjs
  nightfall-client/src/services/withdraw.mjs
  nightfall-client/src/utils/getCommitmentInfo.mjs
  test/adversary/adversary-code/commitment-storage.mjs
  test/adversary/transpile-client-adversary.mjs
  test/e2e/tokens/erc1155.test.mjs
  test/e2e/tokens/erc20.test.mjs
  test/e2e/tokens/erc721.test.mjs
  test/e2e/tokens/l2tokenisation.test.mjs
  test/utils.mjs
  wallet/src/nightfall-browser/services/commitment-storage.js
  wallet/src/nightfall-browser/services/database.js
  wallet/src/nightfall-browser/services/deposit.js
  wallet/src/nightfall-browser/services/transfer.js
  wallet/src/nightfall-browser/services/withdraw.js
  wallet/src/nightfall-browser/utils/getCommitmentInfo.ts
Labels: One more approval needed

#1252 transform service
  cli/lib/nf3.mjs
  config/default.js
  nightfall-client/src/app.mjs
  nightfall-client/src/queues/index.mjs
  nightfall-client/src/queues/transform.mjs
  nightfall-client/src/routes/index.mjs
  nightfall-client/src/routes/transform.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-client/src/services/transform.mjs
  nightfall-client/src/utils/computeCircuitInputs.mjs
  nightfall-client/src/utils/getCommitmentInfo.mjs
  nightfall-client/src/utils/submitTransaction.mjs
  nightfall-deployer/circuits/tokenise.circom
  nightfall-deployer/circuits/transform.circom
  nightfall-deployer/package-lock.json
  test/e2e/tokens/l2tokenisation.test.mjs
  test/unit/circuits/transform.circom.mjs
  worker/src/services/generateProof.mjs
Labels: Required PR

#1327 trusted key bug
  nightfall-deployer/contracts/X509.sol
Labels: Bug
