Repository EYBlockchain/nightfall_3, pull requests merged in 2022-07, with the labels that each got.

#793 remove uneeded code in start-nightfall
  docker-compose.wallet-test.yml
  start-nightfall
Labels: One more approval needed

#715 Luizoamorim/import and export commitments
  wallet/.eslintrc.js
  wallet/babel.config.js
  wallet/jest.config.js
  wallet/package-lock.json
  wallet/package.json
  wallet/src/components/Assets/index.jsx
  wallet/src/components/BridgeComponent/index.jsx
  wallet/src/components/Modals/Bridge/index.tsx
  wallet/src/components/Modals/sendModal.tsx
  wallet/src/components/Tokens/index.jsx
  wallet/src/components/Transactions/index.jsx
  wallet/src/components/Transactions/index.scss
  wallet/src/components/Transactions/withdraw.tsx
  wallet/src/static/supported-token-lists/supported-tokens-local.ts
  wallet/src/utils/CommitmentsBackup/commitmentsVerification.js
  wallet/src/utils/CommitmentsBackup/export.js
  wallet/src/utils/CommitmentsBackup/import.js
  wallet/src/views/wallet/index.jsx
  wallet/tests/unit/utils/CommitmentsBackup/commitmentsVerification.test.js
  wallet/tests/unit/utils/CommitmentsBackup/export.test.js
  wallet/tests/unit/utils/CommitmentsBackup/import.test.js
Labels: One more approval needed

#792 optimist syncing with testnet
  nightfall-optimist/start-optimist.sh
Labels: One more approval needed

#821 bit fix
  nightfall-client/src/classes/commitment.mjs
  nightfall-deployer/circuits/deposit.zok
  nightfall-deployer/circuits/double_transfer.zok
  nightfall-deployer/circuits/single_transfer.zok
  nightfall-deployer/circuits/withdraw.zok
Labels: bug

#807 fix: adapt config for real deployment
  config/default.js
Labels: One more approval needed, changes to deployment

#716 avoid storing redundant tx from blockpropose event
  nightfall-client/src/event-handlers/block-proposed.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-client/src/services/commitment-sync.mjs
  wallet/src/nightfall-browser/event-handlers/block-proposed.js
Labels: One more approval needed

#827 Roger taule/issue820
  common-files/utils/crypto/merkle-tree/utils.mjs
  config/default.js
  docker-compose.adversary.yml
  docker-compose.images.example.yml
  docker-compose.yml
  nightfall-deployer/circuits/common/merkle-tree/path-check.zok
  nightfall-deployer/circuits/double_transfer.zok
  nightfall-deployer/circuits/single_transfer.zok
  nightfall-deployer/circuits/withdraw.zok
  nightfall-deployer/contracts/MerkleTree_Stateless.sol
  nightfall-deployer/contracts/Poseidon.sol
  nightfall-deployer/migrations/2_deploy_upgradeable.js
  nightfall-deployer/migrations/4_upgrade_upgradeable.js
  nightfall-optimist/start-optimist.sh
  package.json
  test/ping-pong/docker-compose.yml
  test/timber.test.mjs
  wallet/src/common-files/utils/crypto/merkle-tree/utils.js
  wallet/src/common-files/utils/crypto/poseidon/poseidon-constants.js
  wallet/src/common-files/utils/crypto/poseidon/poseidon.js
  wallet/tsconfig.json
Labels: One more approval needed, changes to deployment

#831 Mac m1 client fix
  client.Dockerfile
Labels: changes to deployment

#812 refactor aws circuits path in config
  config/default.js
  wallet/src/nightfall-browser/services/fetch-circuit.js
  wallet/src/static/supported-token-lists/supported-tokens-local.ts
  wallet/src/web-worker/index.js
Labels: changes to deployment

#832 fix: error when setting token restrictions
  nightfall-deployer/migrations/2_deploy_upgradeable.js
Labels: changes to deployment
