Repository EYBlockchain/nightfall_3, pull requests merged in 2022-11, with the labels that each got.

#1180 Update wallet remote url
  wallet/package.json
  wallet/public/app_loader.js
Labels: One more approval needed

#1182 Get minimum and block stake from the blockchain
  apps/proposer/config/default.js
  apps/proposer/src/proposer.mjs
  cli/lib/constants.mjs
  cli/lib/nf3.mjs
  config/default.js
  doc/lib/nf3.mjs.html
  test/adversary.test.mjs
  test/circuits.test.mjs
  test/e2e/protocol/proposer.test.mjs
  test/e2e/tokens/erc1155.test.mjs
  test/e2e/tokens/erc20.test.mjs
  test/e2e/tokens/erc721.test.mjs
  test/gas.test.mjs
  test/kyc.test.mjs
  test/multisig/administrator.test.mjs
  test/optimist-resync.test.mjs
  test/ping-pong/ping-pong.test.mjs
  test/utils.mjs
Labels: One more approval needed

#1184 make adversary proposer to submit bad transaction
  cli/lib/nf3.mjs
  common-files/package-lock.json
  nightfall-deployer/contracts/State.sol
  nightfall-deployer/migrations/3_test_tokens_migration.js
  test/adversary.test.mjs
  test/adversary/adversary-code/block-assembler.mjs
  test/adversary/adversary-code/database.mjs
  test/adversary/transpile-adversary.mjs
Labels: DNM, One more approval needed

#1085 Proposer & Optimist little fixes
  cli/lib/nf3.mjs
  common-files/utils/utils.mjs
  nightfall-optimist/src/event-handlers/transaction-submitted.mjs
  nightfall-optimist/src/services/block-assembler.mjs
Labels: SDK

#1221 good test now count rollback counts
  test/e2e/tokens/erc1155.test.mjs
  test/e2e/tokens/erc20.test.mjs
  test/e2e/tokens/erc721.test.mjs
Labels: One more approval needed

#1222 adhoc master adversary test fix (bug fix)
  test/adversary/transpile-adversary.mjs
Labels: Bug

#1264 Chait/optimist fixes
  nightfall-optimist/src/event-handlers/transaction-submitted.mjs
Labels: Required PR

#1255 chore: remove hashing function
  cli/lib/nf3.mjs
  cli/package.json
  config/default.js
  nightfall-optimist/src/utils/auth.mjs
  test/circuits.test.mjs
  test/e2e/protocol/proposer.test.mjs
  test/multisig/administrator.test.mjs
Labels: Required PR

#1246 ChangeCurrentProposer - calculation of the next proposers
  nightfall-deployer/contracts/State.sol
  test/unit/SmartContracts/state.unit.test.mjs
Labels: One more approval needed, Required PR

#1261 several fixes for aws deployment
  .github/workflows/on-pull-request-master.yml
  bin/setup-nightfall
  common-files/utils/web3.mjs
  config/default.js
  docker/docker-compose.apps.yml
  docker/docker-compose.client.yml
  docker/docker-compose.yml
  hosted-utils-api-server/entrypoint.sh
  nightfall-client/src/app.mjs
  nightfall-client/src/index.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-client/start-client
  nightfall-deployer/src/circuit-setup.mjs
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  wallet/package.json
  wallet/src/components/Transactions/index.jsx
  wallet/src/nightfall-browser/services/fetch-circuit.js
  wallet/src/web-worker/index.js
  worker/src/index.mjs
Labels: Required PR
