Repository EYBlockchain/nightfall_3, pull requests merged in 2022-02, with the labels that each got.

#426 Wait for twelve L1 confirmations before updating L2 data.
  .github/workflows/publish-docker-app-images.yml
  .github/workflows/publish-docker-images.yml
  cli/lib/nf3.mjs
  common-files/classes/public-inputs.mjs
  common-files/package-lock.json
  common-files/utils/contract.mjs
  common-files/utils/event-queue.mjs
  compress-keys.mjs
  config/default.js
  docker-compose.ganache.yml
  docker-compose.yml
  nightfall-client/src/event-handlers/block-proposed.mjs
  nightfall-client/src/event-handlers/chain-reorg.mjs
  nightfall-client/src/routes/commitment.mjs
  nightfall-client/src/routes/transfer.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-client/src/services/database.mjs
  nightfall-client/src/services/transfer.mjs
  nightfall-deployer/entrypoint.sh
  nightfall-deployer/migrations/4_test_tokens_migration.js
  nightfall-deployer/src/circuit-setup.mjs
  nightfall-deployer/src/contract-setup.mjs
  nightfall-deployer/truffle-config.js
  nightfall-optimist/src/index.mjs
  package-lock.json
  package.json
  test/http.mjs
  test/neg-http.mjs
  test/ping-pong/docker-compose.host.docker.internal.yml
  test/ping-pong/docker-compose.ropsten.yml
  test/ping-pong/docker-compose.standalone.ganache.yml
  test/ping-pong/docker-compose.yml
  test/ping-pong/user-local/package-lock.json
  test/ping-pong/user-local/package.json
  test/ping-pong/user-local/src/index.mjs
  test/ping-pong/user-local/src/utils.mjs
  test/ping-pong/user-local1/.dockerignore
  test/ping-pong/user-local1/.gitignore
  test/ping-pong/user-local1/Dockerfile
  test/ping-pong/user-local1/docker-entrypoint.sh
  test/ping-pong/user-local1/package-lock.json
  test/ping-pong/user-local1/package.json
  test/ping-pong/user-local1/pre-start-script.sh
  test/ping-pong/user-local1/src/index.mjs
  test/utils.mjs
  wallet/docker-entry.sh
  wallet/test/tx_test.py
Labels: One more approval needed

#402 fix: move initialclientsync to incomingviewingkey
  nightfall-client/src/event-handlers/block-proposed.mjs
  nightfall-client/src/routes/incoming-viewing-key.mjs
  nightfall-client/src/services/commitment-sync.mjs
  nightfall-client/src/services/database.mjs
Labels: One more approval needed

#432 fix: remove length check in invalid txn typecheck
  nightfall-deployer/contracts/ChallengesUtil.sol
Labels: One more approval needed

#498 bug - proposers can register twice
  nightfall-deployer/contracts/Proposers.sol
  test/http.mjs
  test/neg-http.mjs
Labels: bug

#507 github action updated ropsten cronjob on every monday
  .github/workflows/ropsten-deploy-cron-job.yml
  wallet/package-lock.json
  wallet/package.json
Labels: One more approval needed

#508 remove github action workflow - publish docker image
  .github/workflows/publish-docker-app-images.yml
  .github/workflows/publish-docker-images.yml
Labels: One more approval needed

#509 remove ERC addresses from transfer
  nightfall-client/src/services/transfer.mjs
  nightfall-deployer/circuits/double_transfer.zok
  nightfall-deployer/circuits/double_transfer_stub.zok
  nightfall-deployer/circuits/single_transfer.zok
  nightfall-deployer/circuits/single_transfer_stub.zok
  nightfall-optimist/src/services/transaction-checker.mjs
Labels: bug, One more approval needed

#526 Westlad/ping pong fix
  .github/workflows/check-PRs.yml
  test/ping-pong/docker-compose.yml
  test/ping-pong/pong-apps
  test/ping-pong/proposer/src/index.mjs
  test/ping-pong/user-local/Dockerfile
  test/ping-pong/user-local/src/index.mjs
  test/ping-pong/user-local/src/utils.mjs
Labels: bug, One more approval needed
