Repository EYBlockchain/nightfall_3, pull requests merged in 2022-01, with the labels that each got.

#342 David/wallet error msg
  README.md
  wallet/src/constants.js
  wallet/src/store/index.js
  wallet/src/store/message/message.actions.js
  wallet/src/store/message/message.reducer.js
  wallet/src/store/token/token.thunks.js
  wallet/src/store/transactions/transactions.thunks.js
  wallet/src/views/login/login.view.jsx
  wallet/src/views/transactions/components/header-menu/header-menu.view.jsx
  wallet/src/views/transactions/components/wallet-info/wallet-info.view.jsx
Labels: question, One more approval needed

#334 configuration for hosted geth implemented
  .env-cmdrc
  .github/workflows/check-PRs.yml
  .github/workflows/infura-ropsten-deploy-cron-job.yml
  .github/workflows/ropsten-deploy-cron-job.yml
  README.md
  config/default.js
  docker-compose.infura.yml
  docker-compose.ropsten.yml
  nightfall-client/docker-entrypoint.sh
  nightfall-deployer/entrypoint.sh
  nightfall-deployer/migrations/4_test_tokens_migration.js
  nightfall-deployer/src/circuit-setup.mjs
  nightfall-deployer/src/contract-setup.mjs
  nightfall-optimist/docker-entrypoint.sh
  package.json
  start-nightfall
  test/http.mjs
  test/neg-http.mjs
  test/utils.mjs
Labels: One more approval needed

#386 David/wallet erc1155
  .github/workflows/check-PRs.yml
  cli/lib/nf3.mjs
  cli/lib/tokens.mjs
  cli/src/index.mjs
  cli/src/liquidity-provider.mjs
  doc/lib/nf3.mjs.html
  nightfall-client/src/routes/commitment.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-deployer/contracts/ERC1155Mock.sol
  nightfall-deployer/contracts/ERC1155_2Mock.sol
  nightfall-deployer/contracts/ERC721_2Mock.sol
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/migrations/4_test_tokens_migration.js
  test/constants.mjs
  test/e2e/nightfall-sdk.test.mjs
  wallet/Dockerfile
  wallet/README.md
  wallet/public/index.html
  wallet/public/matic-token-icon.svg
  wallet/src/store/token/token.actions.js
  wallet/src/store/token/token.reducer.js
  wallet/src/store/token/token.thunks.js
  wallet/src/store/transactions/transactions.thunks.js
  wallet/src/utils/lib/utils.js
  wallet/src/utils/tokens.js
  wallet/src/views/transactions/components/transactions/transactions-modal.view.jsx
  wallet/src/views/transactions/components/wallet-info/token-add.view.jsx
  wallet/src/views/transactions/components/wallet-info/wallet-info.view.jsx
  wallet/test/constants.py
  wallet/test/effect_test.py
  wallet/test/helpers/metamask.py
  wallet/test/helpers/test.py
  wallet/test/helpers/wallet.py
  wallet/test/login_test.py
  wallet/test/token_test.py
  wallet/test/tx_test.py
  wallet/test/wallet_test.py
Labels: One more approval needed, changes requested

#422 nightfall_browser - web3.js used for approve and submitTransaction
  cli/lib/index.mjs
  wallet/src/common-files/utils/contract.js
  wallet/src/store/transactions/transactions.thunks.js
Labels: DNM

#420 nightfall-browser config refactor
  cli/lib/index.mjs
  wallet/package-lock.json
  wallet/package.json
  wallet/src/common-files/classes/fq2.js
  wallet/src/common-files/classes/timber.js
  wallet/src/common-files/utils/contract.js
  wallet/src/common-files/utils/crypto/merkle-tree/merkle-tree.js
  wallet/src/common-files/utils/crypto/merkle-tree/utils.js
  wallet/src/common-files/utils/crypto/modular-division.js
  wallet/src/common-files/utils/curve-maths/curves.js
  wallet/src/common-files/utils/event-queue.js
  wallet/src/common-files/utils/logger.js
  wallet/src/common-files/utils/web3.js
  wallet/src/index.jsx
  wallet/src/nightfall-browser/classes/secrets.js
  wallet/src/nightfall-browser/event-handlers/block-proposed.js
  wallet/src/nightfall-browser/event-handlers/subscribe.js
  wallet/src/nightfall-browser/services/commitment-storage.js
  wallet/src/nightfall-browser/services/database.js
  wallet/src/nightfall-browser/services/deposit.js
  wallet/src/nightfall-browser/services/finalise-withdrawal.js
  wallet/src/nightfall-browser/services/instant-withdrawal.js
  wallet/src/nightfall-browser/services/keys.js
  wallet/src/nightfall-browser/services/process-calldata.js
  wallet/src/nightfall-browser/services/state-sync.js
  wallet/src/nightfall-browser/services/transfer.js
  wallet/src/nightfall-browser/services/valid-withdrawal.js
  wallet/src/nightfall-browser/services/withdraw.js
  wallet/src/nightfall-browser/utils/crypto/encryption/elgamal.js
  wallet/src/nightfall-browser/utils/crypto/encryption/elligator2.js
  wallet/src/store/transactions/transactions.thunks.js
  wallet/src/utils/parseConfigs.js
Labels: DNM
