Repository EYBlockchain/nightfall_3, pull requests merged in 2022-04, with the labels that each got.

#589 Nonce from pending and fixing nonce order
  .github/workflows/check-PRs.yml
  cli/lib/nf3.mjs
  cli/package-lock.json
  cli/package.json
  nightfall-optimist/src/classes/block.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  package.json
  test/adversary.test.mjs
  test/adversary/adversary-code/block-assembler.mjs
  test/adversary/transpile-adversary.mjs
  test/e2e/protocol/proposer.test.mjs
  test/e2e/tokens/erc20.test.mjs
  test/e2e/tokens/erc721.test.mjs
Labels: PRIORITY 0

#583 (nightfall-browser) web-worker comlink implement to fetch circuits files from s3 bucket
  .github/workflows/browser-e2e-test.yml
  config/default.js
  docker-compose.yml
  hosted-utils-api-server/package-lock.json
  hosted-utils-api-server/package.json
  hosted-utils-api-server/src/index.mjs
  hosted-utils-api-server/src/routes/browser-circuit.mjs
  wallet/package-lock.json
  wallet/package.json
  wallet/src/nightfall-browser/services/fetch-circuit.js
  wallet/src/web-worker/index.js
Labels: One more approval needed, PRIORITY 0

#603 docs: adding contract upgrade document
  doc/upgrading-contracts.md
Labels: One more approval needed

#600 Westlad/proposer robustify
  cli/lib/constants.mjs
  cli/lib/nf3.mjs
  cli/package-lock.json
  cli/package.json
  common-files/package-lock.json
  common-files/package.json
  config/default.js
  nightfall-deployer/contracts/Shield.sol
  nightfall-optimist/src/classes/block.mjs
  nightfall-optimist/src/event-handlers/subscribe.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  nightfall-optimist/src/services/challenges.mjs
  package-lock.json
  package.json
  test/ping-pong/proposer/package-lock.json
  test/ping-pong/proposer/package.json
  test/ping-pong/user-local/package-lock.json
  test/ping-pong/user-local/package.json
Labels: One more approval needed

#608 112 bit transaction value to enable full 18 decimal place range with large integer part
  .eslintignore
  common-files/classes/transaction.mjs
  config/default.js
  nightfall-deployer/contracts/Structures.sol
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/transaction-checker.mjs
  wallet/package-lock.json
  wallet/package.json
  wallet/src/common-files/classes/bigFloat.ts
  wallet/src/common-files/classes/transaction.js
  wallet/src/components/BridgeComponent/index.jsx
  wallet/src/components/Input/index.tsx
  wallet/src/components/Input/masks.ts
  wallet/src/components/Modals/sendModal.tsx
  wallet/src/contract-abis/Shield.json
  wallet/src/hooks/Account/index.tsx
  wallet/src/nightfall-browser/services/commitment-storage.js
  wallet/src/nightfall-browser/services/withdraw.js
  wallet/tests/unit/float.ts
  wallet/tsconfig.json
Labels: One more approval needed, contract change

#615 Local Development Environment For Wallet
  config/default.js
  wallet/README.md
  wallet/craco.config.js
  wallet/package-lock.json
  wallet/package.json
  wallet/src/components/BridgeComponent/index.jsx
  wallet/src/components/Modals/Bridge/index.tsx
  wallet/src/components/Modals/Bridge/styles.scss
  wallet/src/components/Modals/instantWithdrawal.tsx
  wallet/src/components/Modals/sendModal.tsx
  wallet/src/components/Modals/txInfoModal.tsx
  wallet/src/components/TokenItem/index.jsx
  wallet/src/components/Transactions/index.jsx
  wallet/src/hooks/User/index.jsx
  wallet/src/static/supported-token-lists/TokenType.ts
  wallet/src/static/supported-token-lists/index.ts
  wallet/src/static/supported-token-lists/supported-tokens-local.ts
  wallet/src/static/supported-token-lists/supported-tokens-testnet.ts
  wallet/src/views/bridge/index.jsx
  wallet/src/views/transactionPage/index.jsx
  wallet/src/views/wallet/index.jsx
  wallet/src/web-worker/index.js
  wallet/tsconfig.json
  wallet/tsconfig.path.json
Labels: merge conflict, One more approval needed

#628 overflow checks
  config/default.js
  nightfall-client/src/classes/commitment.mjs
  nightfall-client/src/classes/nullifier.mjs
  nightfall-client/src/services/transfer.mjs
  nightfall-deployer/circuits/double_transfer.zok
  nightfall-deployer/circuits/double_transfer_stub.zok
  nightfall-deployer/circuits/single_transfer.zok
  nightfall-deployer/circuits/single_transfer_stub.zok
  nightfall-deployer/circuits/withdraw.zok
  nightfall-deployer/contracts/Challenges.sol
  nightfall-deployer/contracts/ChallengesUtil.sol
  nightfall-deployer/contracts/State.sol
  nightfall-deployer/contracts/Verifier.sol
  nightfall-optimist/src/services/transaction-checker.mjs
  wallet/src/nightfall-browser/classes/commitment.js
  wallet/src/nightfall-browser/classes/nullifier.js
Labels: bug

#612 Westlad/enhanced gas test
  README.md
  nightfall-deployer/src/circuit-setup.mjs
  test/e2e/gas.test.mjs
  test/utils.mjs
Labels: One more approval needed

#632 docs: information on maintaining privacy
  doc/wallet-privacy.md
Labels: PRIORITY 0

#630 blocks can be made at any point in time
  cli/lib/nf3.mjs
  nightfall-optimist/src/routes/block.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  test/e2e/tokens/erc1155.test.mjs
Labels: One more approval needed, PRIORITY 0

#634 add amount restrictions for mainnet and goerli ERC contracts
  config/default.js
  nightfall-deployer/migrations/2_deploy_upgradeable.js
  nightfall-deployer/migrations/3_test_tokens_migration.js
  test/e2e/tokens/erc20.test.mjs
Labels: contract change, PRIORITY 0

#627 Small Wallet Bugs
  wallet/package-lock.json
  wallet/src/common-files/utils/contract.js
  wallet/src/components/BridgeComponent/index.jsx
  wallet/src/web-worker/index.js
  wallet/tsconfig.json
Labels: bug, One more approval needed, PRIORITY 0
