Repository EYBlockchain/nightfall_3, pull requests merged in 2022-09, with the labels that each got.

#870 fix: optimist resync over a bad block, tidy docker-compose yml
  .github/workflows/check-PRs.yml
  cli/lib/environment.mjs
  cli/lib/nf3.mjs
  common-files/classes/transaction.mjs
  common-files/utils/event-queue.mjs
  config/default.js
  docker-compose.client.dev.yml
  docker-compose.client.yml
  docker-compose.dev.yml
  docker-compose.ganache.yml
  docker-compose.host.docker.internal.yml
  docker-compose.images.example.yml
  docker-compose.ropsten.yml
  docker-compose.standalone.geth.yml
  docker-compose.stubs.yml
  docker-compose.yml
  nightfall-client/dropAll.sh
  nightfall-client/start-client
  nightfall-deployer/truffle-config.js
  nightfall-optimist/package-lock.json
  nightfall-optimist/src/classes/block.mjs
  nightfall-optimist/src/event-handlers/block-proposed.mjs
  nightfall-optimist/src/event-handlers/challenge-commit.mjs
  nightfall-optimist/src/event-handlers/rollback.mjs
  nightfall-optimist/src/index.mjs
  nightfall-optimist/src/routes/challenger.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  nightfall-optimist/src/services/block-utils.mjs
  nightfall-optimist/src/services/challenges.mjs
  nightfall-optimist/src/services/database.mjs
  nightfall-optimist/src/services/state-sync.mjs
  package.json
  setup-nightfall
  start-nightfall
  test/adversary.test.mjs
  test/adversary/transpile-adversary.mjs
  test/e2e/circuits.test.mjs
  test/e2e/gas.test.mjs
  test/e2e/protocol/challenger.test.mjs
  test/e2e/tokens/erc20.test.mjs
  test/optimist-resync.test.mjs
  test/ping-pong/docker-compose.standalone.ganache.yml
  test/ping-pong/docker-compose.yml
  test/rollback-resync.test.mjs
  test/utils.mjs
  worker.Dockerfile
Labels: One more approval needed

#823 Stuffing ping-pong in a mocha test
  .github/workflows/check-PRs.yml
  apps/proposer/config/default.js
  apps/proposer/package-lock.json
  apps/proposer/package.json
  apps/proposer/src/app.mjs
  apps/proposer/src/proposer.mjs
  apps/proposer/src/routes/contract-address.mjs
  apps/proposer/src/routes/proposer.mjs
  cli/lib/nf3.mjs
  cli/lib/tokens.mjs
  config/default.js
  docker-compose.yml
  package.json
  proposer.Dockerfile
  start-nightfall
  test/e2e/circuits.test.mjs
  test/e2e/protocol/health-and-contracts.test.mjs
  test/ping-pong/README.md
  test/ping-pong/docker-compose.host.docker.internal.yml
  test/ping-pong/docker-compose.ropsten.yml
  test/ping-pong/docker-compose.standalone.ganache.yml
  test/ping-pong/docker-compose.stubs.yml
  test/ping-pong/docker-compose.yml
  test/ping-pong/ganache-standalone
  test/ping-pong/index.mjs
  test/ping-pong/ping-pong.test.mjs
  test/ping-pong/pong-apps
  test/ping-pong/pong-down
  test/ping-pong/pong-nightfall
  test/ping-pong/user-local/.dockerignore
  test/ping-pong/user-local/.gitignore
  test/ping-pong/user-local/docker-entrypoint.sh
  test/ping-pong/user-local/package-lock.json
  test/ping-pong/user-local/package.json
  test/ping-pong/user-local/src/utils.mjs
  test/utils.mjs
  user-local.Dockerfile
  zokrates-worker/src/services/generateProof.mjs
Labels: DNM, changes requested, changes to deployment

#904 add historic root error case for proof verification challenge
  nightfall-deployer/contracts/Challenges.sol
  nightfall-deployer/contracts/Utils.sol
  nightfall-optimist/src/services/challenges.mjs
  nightfall-optimist/src/services/transaction-checker.mjs
  start-nightfall
  test/adversary/adversary-code/block.mjs
  test/adversary/adversary-code/database.mjs
Labels: changes requested

#917 Optimizing challenges
  nightfall-deployer/contracts/Challenges.sol
  nightfall-deployer/contracts/ChallengesUtil.sol
  nightfall-deployer/contracts/State.sol
  nightfall-deployer/contracts/Structures.sol
  nightfall-optimist/src/classes/block.mjs
  nightfall-optimist/src/routes/transaction.mjs
  nightfall-optimist/src/services/challenges.mjs
  nightfall-optimist/src/services/check-block.mjs
  nightfall-optimist/src/services/database.mjs
  nightfall-optimist/src/services/process-calldata.mjs
  nightfall-optimist/src/services/state-sync.mjs
  nightfall-optimist/src/services/transaction-checker.mjs
  test/adversary/transpile-adversary.mjs
Labels: BREAKING CHANGE

#996 fix: setup contracts script
  nightfall-deployer/src/contract-setup.mjs
Labels: One more approval needed

#993 clarify question in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: One more approval needed

#1005 fix: typos in script
  setup-nightfall
Labels: One more approval needed, Bug

#980 docs: what is a proposer
  cli/lib/nf3.mjs
  nightfall-optimist/src/routes/proposer.mjs
Labels: One more approval needed

#984 Test administrator features with multisig
  cli/lib/nf3.mjs
  nightfall-administrator/src/services/contract-transactions.mjs
  nightfall-administrator/src/services/helpers.mjs
  nightfall-administrator/src/ui/get-info.mjs
  nightfall-administrator/src/ui/menu.mjs
  package.json
  test/multisig/administrator.test.mjs
  test/multisig/multisig.mjs
  test/multisig/nightfall-multisig.mjs
Labels: One more approval needed

#1011 Several deployment fixes
  apps/challenger/src/challenger.mjs
  nightfall-deployer/src/contract-setup.mjs
Labels: One more approval needed

#1019 fix: 'cannot find cls-hooked' bug in master
  setup-nightfall
Labels: Bug

#924 fix: start sdk substitution from tests
  package-lock.json
  package.json
  test/e2e/protocol/health-and-contracts.test.mjs
Labels: One more approval needed, SDK

#896 Implement PoS for proposers
  .github/workflows/check-PRs.yml
  apps/proposer/config/default.js
  apps/proposer/src/proposer.mjs
  cli/lib/nf3.mjs
  config/default.js
  nightfall-deployer/contracts/Config.sol
  nightfall-deployer/contracts/Proposers.sol
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/contracts/State.sol
  nightfall-deployer/contracts/Structures.sol
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/database.mjs
  test/adversary.test.mjs
  test/circuits.test.mjs
  test/e2e/protocol/proposer.test.mjs
  test/e2e/tokens/erc1155.test.mjs
  test/e2e/tokens/erc20.test.mjs
  test/e2e/tokens/erc721.test.mjs
  test/gas.test.mjs
  test/optimist-resync.test.mjs
  test/ping-pong/ping-pong.test.mjs
  test/utils.mjs
Labels: One more approval needed, SDK, Changes to deployment
