Repository EYBlockchain/nightfall_3, pull requests merged in 2022-05, with the labels that each got.

#636 add params for aws ganache
  config/default.js
Labels: PRIORITY 0

#639 transactionHashesRoot calculated in proposeBlock without challenge
  common-files/classes/transaction.mjs
  config/default.js
  nightfall-client/src/event-handlers/block-proposed.mjs
  nightfall-client/src/services/database.mjs
  nightfall-client/src/services/finalise-withdrawal.mjs
  nightfall-client/src/services/instant-withdrawal.mjs
  nightfall-client/src/services/process-calldata.mjs
  nightfall-client/src/services/valid-withdrawal.mjs
  nightfall-deployer/contracts/Challenges.sol
  nightfall-deployer/contracts/ChallengesUtil.sol
  nightfall-deployer/contracts/MerkleTree_Stateless_KECCAK.sol
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/contracts/State.sol
  nightfall-deployer/contracts/Utils.sol
  nightfall-deployer/migrations/2_deploy_upgradeable.js
  nightfall-deployer/migrations/4_upgrade_upgradeable.js
  nightfall-optimist/src/classes/block.mjs
  nightfall-optimist/src/services/challenges.mjs
  nightfall-optimist/src/services/check-block.mjs
  nightfall-optimist/src/services/process-calldata.mjs
  wallet/src/common-files/classes/transaction.js
  wallet/src/contract-abis/Shield.json
  wallet/src/nightfall-browser/event-handlers/block-proposed.js
  wallet/src/nightfall-browser/services/commitment-storage.js
  wallet/src/nightfall-browser/services/database.js
  wallet/src/nightfall-browser/services/finalise-withdrawal.js
  wallet/src/nightfall-browser/services/instant-withdrawal.js
  wallet/src/nightfall-browser/services/process-calldata.js
  wallet/src/nightfall-browser/services/valid-withdrawal.js
  wallet/src/static/supported-token-lists/supported-tokens-local.ts
Labels: One more approval needed, contract change, PRIORITY 0

#641 Save external offchain transactions in optimist
  .eslintignore
  common-files/utils/crypto/multihash.mjs
  nightfall-deployer/migrations/2_deploy_upgradeable.js
  nightfall-optimist/src/event-handlers/block-proposed.mjs
  nightfall-optimist/src/services/state-sync.mjs
Labels: PRIORITY 0

#645 Browser-fixes-1
  wallet/src/assets/lottie/check-mark-cross.json
  wallet/src/components/BridgeComponent/index.jsx
  wallet/src/components/Modals/sendModal.tsx
  wallet/src/nightfall-browser/services/deposit.js
  wallet/src/nightfall-browser/services/transfer.js
  wallet/src/nightfall-browser/services/withdraw.js
Labels: bug, PRIORITY 0

#642 fix offchain connection and tests
  nightfall-client/src/services/transfer.mjs
  nightfall-client/src/services/withdraw.mjs
  test/e2e/tokens/erc20.test.mjs
Labels: bug

#648 Update restrictions
  config/default.js
  nightfall-deployer/contracts/Config.sol
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/migrations/2_deploy_upgradeable.js
  nightfall-deployer/migrations/3_test_tokens_migration.js
  test/e2e/tokens/erc20.test.mjs
  test/utils.mjs
Labels: One more approval needed, PRIORITY 0

#650 fix more syncing issues
  common-files/utils/event-queue.mjs
  nightfall-optimist/src/event-handlers/block-proposed.mjs
  nightfall-optimist/src/event-handlers/subscribe.mjs
  nightfall-optimist/src/index.mjs
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/database.mjs
  nightfall-optimist/src/services/state-sync.mjs
  package.json
Labels: bug, PRIORITY 0

#652 Fix: Mark block stake as withdrawn for the block
  nightfall-deployer/contracts/Shield.sol
Labels: bug, contract change, PRIORITY 0

#653 Apply check-effect-interaction pattern to contract.
  nightfall-deployer/contracts/Shield.sol
Labels: contract change

#654 Configurable gas_multiplier
  cli/lib/constants.mjs
  cli/lib/nf3.mjs
Labels: One more approval needed, MAINNET

#655 capture timeouts in deposit
  test/ping-pong/user-local/src/index.mjs
Labels: One more approval needed

#658 blocknumberL2 -> blockNumberL2
  nightfall-optimist/src/event-handlers/block-proposed.mjs
Labels: bug, PRIORITY 0

#649 feat: adding transferShieldBalance
  nightfall-deployer/contracts/ERCInterface.sol
  nightfall-deployer/contracts/Shield.sol
Labels: contract change, PRIORITY 0

#671 Better estimating of proposer gas price and gas limit
  cli/lib/constants.mjs
  cli/lib/nf3.mjs
Labels: question

#669 fix: challenge historic root
  nightfall-deployer/contracts/Challenges.sol
Labels: One more approval needed

#657 resync cleanup
  common-files/utils/event-queue.mjs
  nightfall-client/src/services/state-sync.mjs
  nightfall-optimist/src/event-handlers/subscribe.mjs
  nightfall-optimist/src/index.mjs
  nightfall-optimist/src/services/state-sync.mjs
Labels: question, One more approval needed

#662 fix: erc20 test race condition
  test/e2e/tokens/erc20.test.mjs
Labels: One more approval needed

#678 remove unnecessary deploys
  nightfall-deployer/migrations/2_deploy_upgradeable.js
Labels: bug
