Repository EYBlockchain/nightfall_3, pull requests merged in 2022-10, with the labels that each got.

#958 KYC backend functionality
  .eslintignore
  .github/workflows/check-PRs.yml
  .gitignore
  cli/lib/nf3.mjs
  config/default.js
  doc/kyc.md
  docker/docker-compose.yml
  hardhat.config.ts
  nightfall-client/src/app.mjs
  nightfall-client/src/routes/index.mjs
  nightfall-client/src/routes/kyc.mjs
  nightfall-client/src/services/kyc.mjs
  nightfall-deployer/contracts/Config.sol
  nightfall-deployer/contracts/KYC.sol
  nightfall-deployer/contracts/Key_Registry.sol
  nightfall-deployer/contracts/Ownable.sol
  nightfall-deployer/contracts/Pausable.sol
  nightfall-deployer/contracts/Proposers.sol
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/contracts/State.sol
  nightfall-deployer/contracts/Stateful.sol
  nightfall-deployer/migrations/2_deploy_upgradeable.js
  nightfall-deployer/package-lock.json
  nightfall-deployer/package.json
  package-lock.json
  package.json
  test/kyc.test.mjs
  test/unit/kyc.unit.test.mjs
Labels: SDK

#1049 save transaction
  nightfall-optimist/src/event-handlers/transaction-submitted.mjs
Labels: One more approval needed

#1036 Add methods update parameters PoS
  .github/workflows/check-PRs.yml
  doc/how_it_works.md
  doc/pos.md
  nightfall-deployer/contracts/Challenges.sol
  nightfall-deployer/contracts/Config.sol
  nightfall-deployer/contracts/Proposers.sol
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/contracts/State.sol
  test/multisig/administrator.test.mjs
  test/multisig/nightfall-multisig.mjs
Labels: One more approval needed, Contract change

#1047 do not register second proposer in ping pong test in AWS
  common-files/utils/contract.mjs
  test/ping-pong/ping-pong.test.mjs
Labels: One more approval needed

#1075 Adding Mongodb service to client's docker-compose
  common-files/utils/httputils.mjs
  docker/docker-compose.client.dev.yml
  docker/docker-compose.client.yml
  zokrates-worker/src/index.mjs
Labels: One more approval needed

#1064 Proposer fee endpoint and update
  apps/proposer/src/routes/proposer.mjs
  cli/lib/nf3.mjs
  nightfall-deployer/contracts/Proposers.sol
  nightfall-deployer/contracts/State.sol
  nightfall-deployer/contracts/Structures.sol
  nightfall-optimist/src/routes/proposer.mjs
  test/adversary.test.mjs
  test/circuits.test.mjs
  test/e2e/protocol/proposer.test.mjs
  test/e2e/tokens/erc1155.test.mjs
  test/e2e/tokens/erc20.test.mjs
  test/e2e/tokens/erc721.test.mjs
  test/gas.test.mjs
  test/kyc.test.mjs
  test/multisig/administrator.test.mjs
  test/utils.mjs
Labels: One more approval needed, Contract change

#1094 PoS minor fixes
  nightfall-deployer/contracts/Challenges.sol
  nightfall-deployer/contracts/Config.sol
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/contracts/State.sol
  nightfall-deployer/contracts/Structures.sol
  test/unit/SmartContracts/shield.unit.test.mjs
  test/unit/utils/shieldStorage.mjs
  test/unit/utils/stateStorage.mjs
Labels: One more approval needed

#1078 David/backup state
  .dockerignore
  .eslintignore
  .github/workflows/on-pull-request-master.yml
  .gitignore
  README.md
  bin/export-nightfall
  bin/geth-standalone
  bin/import-nightfall
  bin/liquidity-provider
  bin/setup-nightfall
  bin/start-apps
  bin/start-nightfall
  docker/docker-compose.standalone.geth.yml
  geth-standalone
Labels: One more approval needed

#1093 Multiple L2 blocks per l1 block
  cli/lib/nf3.mjs
  cli/package-lock.json
  cli/package.json
  config/default.js
  nightfall-deployer/contracts/Config.sol
  nightfall-deployer/contracts/State.sol
  nightfall-optimist/src/classes/block.mjs
  nightfall-optimist/src/services/check-block.mjs
  package-lock.json
  package.json
Labels: SDK

#1041 add aws edge to truffle
  config/default.js
  docker/docker-compose.polygon-edge.yml
  nightfall-deployer/truffle-config.js
Labels: One more approval needed

#1074 Testnet client
  .github/workflows/on-pull-request-master.yml
  docker/docker-compose.client.dev.yml
  docker/docker-compose.client.yml
  nightfall-client/README.md
  nightfall-client/client-example.env
  nightfall-client/start-client
  test/gas.test.mjs
Labels: One more approval needed

#1098 Obfuscating sensitive data whatever the environment
  common-files/package-lock.json
  common-files/package.json
  common-files/test/utils.test.mjs
  common-files/utils/httputils.mjs
  common-files/utils/utils.mjs
  docker/admin.Dockerfile
  docker/client.Dockerfile
  docker/deployer.Dockerfile
  docker/optimist.Dockerfile
  docker/optimist.standalone.Dockerfile
  docker/proposer.Dockerfile
  docker/worker.Dockerfile
Labels: One more approval needed

#1146 Fixed gas and resync tests
  common-files/utils/mongo.mjs
  test/gas.test.mjs
Labels: One more approval needed

#1155 Shield Contract minor optimization
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/contracts/Structures.sol
  test/unit/SmartContracts/shield.unit.test.mjs
  test/unit/utils/shieldStorage.mjs
Labels: One more approval needed

#1137 Add ALWAYS_DO_TRUSTED_SETUP to deployer container
  docker/docker-compose.yml
Labels: One more approval needed
