Repository EYBlockchain/nightfall_3, pull requests merged in 2022-03, with the labels that each got.

#546 Proposer add logging and registration check
  cli/lib/nf3.mjs
  cli/package-lock.json
  cli/package.json
  common-files/package-lock.json
  common-files/package.json
  nightfall-optimist/src/routes/proposer.mjs
  package-lock.json
  package.json
  proposer.Dockerfile
  test/ping-pong/proposer/package.json
  test/ping-pong/proposer/pre-start-script.sh
  test/ping-pong/proposer/src/index.mjs
  test/ping-pong/user-local/package.json
  test/ping-pong/user-local/pre-start-script.sh
  test/ping-pong/user-local/src/index.mjs
  user-local.Dockerfile
  user-local1.Dockerfile
Labels: bug, changes requested

#514 David/staging
  cli/package-lock.json
  common-files/package-lock.json
  common-files/package.json
  common-files/utils/aws-secrets.mjs
  common-files/utils/mongo.mjs
  config/default.js
  nightfall-client/package-lock.json
  nightfall-client/package.json
  nightfall-deployer/truffle-config.js
  nightfall-optimist/package-lock.json
  nightfall-optimist/package.json
  package-lock.json
  test/ping-pong/proposer/package-lock.json
  test/ping-pong/proposer/package.json
  test/ping-pong/proposer/src/app.mjs
  test/ping-pong/proposer/src/index.mjs
Labels: One more approval needed

#563 remove public inputs
  common-files/classes/public-inputs.mjs
  common-files/classes/transaction.mjs
  common-files/utils/crypto/sha256.mjs
  nightfall-client/src/classes/index.mjs
  nightfall-client/src/services/deposit.mjs
  nightfall-client/src/services/transfer.mjs
  nightfall-client/src/services/withdraw.mjs
  nightfall-optimist/src/classes/index.mjs
  nightfall-optimist/src/services/transaction-checker.mjs
Labels: One more approval needed

#553 Proposer to propose multiple L2 blocks at once
  cli/lib/nf3.mjs
  nightfall-optimist/src/classes/block.mjs
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  test/adversary/adversary-code/block-assembler.mjs
  test/adversary/transpile-adversary.mjs
  test/e2e/protocol/proposer.test.mjs
  test/utils.mjs
Labels: One more approval needed

#550 feat: adding a restriction to proposers and challenger 🤌
  common-files/utils/web3.mjs
  config/default.js
  docker-compose.ganache.yml
  docker-compose.infura.yml
  nightfall-client/docker-entrypoint.sh
  nightfall-deployer/contracts/Challenges.sol
  nightfall-deployer/contracts/Config.sol
  nightfall-deployer/contracts/Proposers.sol
  nightfall-deployer/entrypoint.sh
  nightfall-deployer/migrations/2_deploy_upgradeable.js
  nightfall-deployer/migrations/3_test_tokens_migration.js
  nightfall-deployer/src/circuit-setup.mjs
  nightfall-deployer/src/contract-setup.mjs
  nightfall-optimist/docker-entrypoint.sh
  package-lock.json
  package.json
  start-nightfall
  test/e2e/protocol/challenger.test.mjs
  test/e2e/protocol/proposer.test.mjs
  test/e2e/tokens/erc20.test.mjs
  test/neg-http.mjs
  test/ping-pong/docker-compose.host.docker.internal.yml
  test/ping-pong/docker-compose.ropsten.yml
  test/ping-pong/docker-compose.standalone.ganache.yml
  test/ping-pong/docker-compose.yml
  test/ping-pong/proposer/src/app.mjs
  test/ping-pong/proposer/src/index.mjs
  test/ping-pong/user-local/src/index.mjs
  test/utils.mjs
Labels: question

#564 Westlad/fix restart nightfall
  cli/lib/nf3.mjs
  common-files/utils/contract.mjs
  config/default.js
  doc/contract-update.md
  doc/contract-upgrade.png
  nightfall-client/src/event-handlers/subscribe.mjs
  nightfall-client/src/services/database.mjs
  nightfall-client/src/services/state-sync.mjs
  nightfall-deployer/src/index.mjs
  nightfall-optimist/src/event-handlers/subscribe.mjs
  nightfall-optimist/src/index.mjs
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/database.mjs
  nightfall-optimist/src/services/proposer.mjs
  package.json
  test/e2e/protocol/proposer.test.mjs
  test/ping-pong/pong-down
  test/ping-pong/proposer/src/index.mjs
Labels: bug-fix, PRIORITY 0

#585 Missing `.block` when accessing historical blocks.
  wallet/src/hooks/User/index.jsx
Labels: bug-fix, PRIORITY 0

#594 several fixes to increase reliability on staging
  cli/lib/nf3.mjs
  common-files/utils/mongo.mjs
  config/default.js
  nightfall-deployer/migrations/3_test_tokens_migration.js
  nightfall-optimist/src/event-handlers/block-proposed.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  test/ping-pong/user-local/src/index.mjs
Labels: PRIORITY 0
