Repository EYBlockchain/nightfall_3, pull requests merged in 2022-08, with the labels that each got.

#824 Israelboudoux/docker improvements
  admin.Dockerfile
  client.Dockerfile
  deployer.Dockerfile
  doc/diagrams/Deposit.png
  doc/diagrams/README.md
  doc/diagrams/deposit.webseqdiagram
  docker-compose.client.yml
  docker-compose.dev.yml
  docker-compose.host.docker.internal.yml
  docker-compose.images.example.yml
  docker-compose.yml
  optimist.Dockerfile
  optimist.standalone.Dockerfile
  proposer.Dockerfile
  user-local.Dockerfile
  worker.Dockerfile
  zokrates.Dockerfile
Labels: changes to deployment

#795 feat: adding ack to block produced websocket 🔌
  cli/lib/nf3.mjs
  common-files/utils/websocket.mjs
  nightfall-optimist/src/event-handlers/chain-reorg.mjs
  nightfall-optimist/src/event-handlers/index.mjs
  nightfall-optimist/src/event-handlers/subscribe.mjs
  nightfall-optimist/src/index.mjs
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  nightfall-optimist/src/services/state-sync.mjs
  nightfall-optimist/src/services/transaction-checker.mjs
  nightfall-optimist/src/utils/index.mjs
Labels: One more approval needed, changes requested

#839 refactor done seprated constants from config
  common-files/classes/timber.mjs
  common-files/classes/transaction.mjs
  common-files/constants/constants.json
  common-files/constants/index.mjs
  config/default.js
  nightfall-administrator/src/services/contract-transactions.mjs
  nightfall-client/src/event-handlers/block-proposed.mjs
  nightfall-client/src/event-handlers/subscribe.mjs
  nightfall-client/src/services/commitment-sync.mjs
  nightfall-client/src/services/database.mjs
  nightfall-client/src/services/deposit.mjs
  nightfall-client/src/services/finalise-withdrawal.mjs
  nightfall-client/src/services/instant-withdrawal.mjs
  nightfall-client/src/services/peers.mjs
  nightfall-client/src/services/process-calldata.mjs
  nightfall-client/src/services/state-sync.mjs
  nightfall-client/src/services/transfer.mjs
  nightfall-client/src/services/valid-withdrawal.mjs
  nightfall-client/src/services/withdraw.mjs
  nightfall-optimist/src/classes/block.mjs
  nightfall-optimist/src/event-handlers/block-proposed.mjs
  nightfall-optimist/src/event-handlers/chain-reorg.mjs
  nightfall-optimist/src/event-handlers/rollback.mjs
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  nightfall-optimist/src/services/challenges.mjs
  nightfall-optimist/src/services/database.mjs
  nightfall-optimist/src/services/instant-withdrawal.mjs
  nightfall-optimist/src/services/process-calldata.mjs
  nightfall-optimist/src/services/proposer.mjs
  nightfall-optimist/src/services/state-sync.mjs
  nightfall-optimist/src/services/transaction-checker.mjs
  nightfall-optimist/src/utils/index.mjs
  test/adversary/adversary-code/database.mjs
  test/timber.test.mjs
  wallet/config/webpack.config.js
  wallet/src/common-files/classes/timber.js
  wallet/src/common-files/classes/transaction.js
  wallet/src/components/Transactions/index.jsx
  wallet/src/index.jsx
  wallet/src/nightfall-browser/classes/secrets.js
  wallet/src/nightfall-browser/event-handlers/block-proposed.js
  wallet/src/nightfall-browser/event-handlers/subscribe.js
  wallet/src/nightfall-browser/services/database.js
  wallet/src/nightfall-browser/services/deposit.js
  wallet/src/nightfall-browser/services/finalise-withdrawal.js
  wallet/src/nightfall-browser/services/instant-withdrawal.js
  wallet/src/nightfall-browser/services/process-calldata.js
  wallet/src/nightfall-browser/services/state-sync.js
  wallet/src/nightfall-browser/services/transfer.js
  wallet/src/nightfall-browser/services/valid-withdrawal.js
  wallet/src/nightfall-browser/services/withdraw.js
  wallet/src/utils/lib/local-storage.js
  wallet/src/utils/parseConfigs.js
Labels: One more approval needed, changes to deployment

#850 security vulnerabilities fixes
  package-lock.json
  package.json
  test/ping-pong/user-local/package-lock.json
  test/ping-pong/user-local/package.json
  zokrates-worker/package-lock.json
  zokrates-worker/package.json
Labels: One more approval needed

#799 (wallet/nightfall bowser) refactor fetch circuits files
  wallet/package-lock.json
  wallet/src/nightfall-browser/services/fetch-circuit.js
  wallet/src/static/supported-token-lists/supported-tokens-local.ts
  zokrates-worker/src/zokrates-lib/compile.mjs
Labels: DNM, changes to deployment

#845 Several fixes
  cli/lib/nf3.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-deployer/contracts/mocks/ERC721Mock.sol
  nightfall-optimist/src/routes/block.mjs
  nightfall-optimist/src/services/block-assembler.mjs
  nightfall-optimist/src/services/database.mjs
  test/e2e/tokens/erc1155.test.mjs
  test/ping-pong/user-local/src/index.mjs
Labels: changes to deployment

#873 ErcAddress and fee address check
  nightfall-client/src/services/transfer.mjs
  nightfall-client/src/services/withdraw.mjs
Labels: One more approval needed

#861 David/wallet sync circuits blocks
  config/default.js
  hosted-utils-api-server/Dockerfile
  hosted-utils-api-server/entrypoint.sh
  wallet/.internal.env
  wallet/package-lock.json
  wallet/package.json
  wallet/src/@types/globals.d.ts
  wallet/src/common-files/utils/web3.js
  wallet/src/hooks/User/index.jsx
  wallet/src/nightfall-browser/services/commitment-storage.js
  wallet/src/nightfall-browser/services/confirm-block.js
  wallet/src/nightfall-browser/services/database.js
  wallet/src/nightfall-browser/services/deposit.js
  wallet/src/nightfall-browser/services/fetch-circuit.js
  wallet/src/nightfall-browser/services/transfer.js
  wallet/src/nightfall-browser/services/withdraw.js
  wallet/src/static/supported-token-lists/index.ts
  wallet/src/utils/lib/key-storage.ts
  wallet/src/web-worker/index.js
Labels: DNM

#886 Improving GitHub Actions tests
  .github/workflows/check-PRs.yml
  common-files/package-lock.json
  common-files/package.json
  common-files/test/compression.test.mjs
  common-files/test/fq2.test.mjs
  common-files/test/poseidon.test.mjs
  package.json
  test/neg-http.mjs
Labels: One more approval needed

#872 Payments refactor
  common-files/classes/transaction.mjs
  common-files/constants/constants.json
  config/default.js
  doc/commitment_selection.md
  nightfall-client/src/event-handlers/block-proposed.mjs
  nightfall-client/src/services/commitment-storage.mjs
  nightfall-client/src/services/deposit.mjs
  nightfall-client/src/services/process-calldata.mjs
  nightfall-client/src/services/transfer.mjs
  nightfall-client/src/services/withdraw.mjs
  nightfall-client/src/utils/computeCircuitInputs.mjs
  nightfall-client/src/utils/getCommitmentInfo.mjs
  nightfall-deployer/circuits/common/generic_circuit/Verifiers/verify_commitments.zok
  nightfall-deployer/circuits/common/generic_circuit/Verifiers/verify_nullifiers.zok
  nightfall-deployer/circuits/common/generic_circuit/Verifiers/verify_structure.zok
  nightfall-deployer/circuits/common/utils/structures.zok
  nightfall-deployer/circuits/deposit.zok
  nightfall-deployer/circuits/deposit_stub.zok
  nightfall-deployer/circuits/transfer.zok
  nightfall-deployer/circuits/transfer_stub.zok
  nightfall-deployer/circuits/withdraw.zok
  nightfall-deployer/circuits/withdraw_stub.zok
  nightfall-deployer/contracts/Challenges.sol
  nightfall-deployer/contracts/ChallengesUtil.sol
  nightfall-deployer/contracts/Shield.sol
  nightfall-deployer/contracts/Structures.sol
  nightfall-deployer/contracts/Utils.sol
  nightfall-optimist/src/classes/block.mjs
  nightfall-optimist/src/event-handlers/block-proposed.mjs
  nightfall-optimist/src/event-handlers/rollback.mjs
  nightfall-optimist/src/event-handlers/transaction-submitted.mjs
  nightfall-optimist/src/routes/proposer.mjs
  nightfall-optimist/src/services/challenges.mjs
  nightfall-optimist/src/services/check-block.mjs
  nightfall-optimist/src/services/process-calldata.mjs
  nightfall-optimist/src/services/transaction-checker.mjs
  test/e2e/tokens/erc20.test.mjs
  wallet/src/common-files/classes/transaction.js
  wallet/src/components/Transactions/index.jsx
  wallet/src/contract-abis/Shield.json
  wallet/src/nightfall-browser/event-handlers/block-proposed.js
  wallet/src/nightfall-browser/services/commitment-storage.js
  wallet/src/nightfall-browser/services/database.js
  wallet/src/nightfall-browser/services/deposit.js
  wallet/src/nightfall-browser/services/process-calldata.js
  wallet/src/nightfall-browser/services/transfer.js
  wallet/src/nightfall-browser/services/withdraw.js
  wallet/src/nightfall-browser/utils/compute-witness.ts
  wallet/src/nightfall-browser/utils/getCommitmentInfo.ts
Labels: changes to deployment

#894 Incorrect right-sibling hash
  nightfall-deployer/contracts/MerkleTree_Stateless.sol
Labels: bug
