Repository EYBlockchain/nightfall_3, pull requests merged in 2023-03, with the labels that each got.

#1395 Configure solcover (Solidity Coverage)
  .solcover.js
  package-lock.json
  package.json
Labels: One more approval needed

#1408 fix: add salt to challenge
  nightfall-deployer/contracts/Challenges.sol
  nightfall-optimist/src/services/challenges.mjs
  test/adversary.test.mjs
  test/unit/SmartContracts/challenges.unit.test.mjs
Labels: Bug

#1409 fix: do not throw if a proposer fails to respond
  nightfall-client/src/utils/submitTransaction.mjs
Labels: One more approval needed, Bug
